### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by wendellm** [andyedinborough/RazorJS#2]
Hi I wanted to test if razorjs could generate anything else besides html so I created this gulp file:

var Razor = require('razorjs');
var gulp = require('gulp')
var file = require('gulp-file');

gulp.task('default', function() {
    var str = Razor.compile('hello @model.name')({ name: 'world' });
    return file('something.js', str, { src: true }).pipe(gulp.dest('dist'));
});

But I got the following and I doing something wrong or is this lib just too old?

TypeError: object is not a function
    at Gulp.<anonymous> (c:\dev\framework\mah.ngen\gulpfile.js:10:49)
    at module.exports (c:\dev\framework\mah.ngen\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (c:\dev\framework\mah.ngen\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (c:\dev\framework\mah.ngen\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (c:\dev\framework\mah.ngen\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\Users\wendellm\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Module.runMain [as _onTimeout] (module.js:503:11)
    at Timer.listOnTimeout (timers.js:110:15)

**Comment by andyedinborough** [comment]
Try `Razor.render(...)` instead of `compile`.  `Razor.compile(...)` returns a function that you can cache and execute over and over again with different models.  `Razor.render(...)` parses and executes that function with the given model.

**Comment by wendellm** [comment]
HI thanks for replying.

I tried again with: both compile and render same result ... object is not a function

var path = require('path');
var jetpack = require('fs-jetpack');
var Razor = require('razorjs');

module.exports = function() {

    var template = Razor.compile('hello @model.name');
    var str = template({ name: 'world' });
    // var str = Razor.render('hello @model.name')({ name: 'world' });
    // Creates file with mode '777' and content 'Hello World!'
    jetpack.file(path.normalize('c:/dev/framework/mah.ngen/test.txt'), { mode: '777', content: str });
};

**Comment by andyedinborough** [comment]
Are you referencing the node build of razorjs, https://github.com/andyedinborough/RazorJS/blob/master/bin/node/razor.js?  It's slightly different from the browser version.

**Comment by wendellm** [comment]
Yup, awesome that worked.. thanks
